# Generated by Django 3.0.1 on 2021-03-22 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_auto_20210125_1722'),
        ('users', '0006_customuser_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsWishlist', to='shop.Product'),
        ),
    ]
