# Generated by Django 3.0.1 on 2020-11-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage_main_banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_english', models.URLField()),
                ('link_arabic', models.URLField()),
                ('banner_title', models.CharField(max_length=154)),
                ('banner_image', models.ImageField(upload_to='media/', verbose_name='Photo 640x400')),
            ],
        ),
    ]
