# Generated by Django 3.0.1 on 2020-12-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage_main_banners',
            name='banner_image',
            field=models.ImageField(upload_to='media/', verbose_name='Photo 1920x720'),
        ),
    ]
