# Generated by Django 3.0.1 on 2021-01-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201215_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Photo_Uploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/', verbose_name='photo 270x270')),
                ('image3', models.ImageField(null=True, upload_to='media/', verbose_name='photo 800x800')),
            ],
        ),
    ]
