# Generated by Django 3.0.1 on 2021-01-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_products_photo_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_photo_uploader',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to='media/', verbose_name='photo 270x270'),
        ),
        migrations.AlterField(
            model_name='products_photo_uploader',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 800x800'),
        ),
    ]
