# Generated by Django 3.0.1 on 2021-01-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210103_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Photo_Uploader_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 800x800')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 800x800')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 800x800')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 800x800')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 800x800')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 800x800')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 800x800')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 800x800')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 800x800')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 800x800')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 800x800')),
            ],
        ),
        migrations.AddField(
            model_name='products_photo_uploader',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 270x270'),
        ),
        migrations.AddField(
            model_name='products_photo_uploader',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 270x270'),
        ),
        migrations.AddField(
            model_name='products_photo_uploader',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 270x270'),
        ),
        migrations.AddField(
            model_name='products_photo_uploader',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 270x270'),
        ),
        migrations.AddField(
            model_name='products_photo_uploader',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 270x270'),
        ),
        migrations.AddField(
            model_name='products_photo_uploader',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 270x270'),
        ),
        migrations.AddField(
            model_name='products_photo_uploader',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 270x270'),
        ),
        migrations.AddField(
            model_name='products_photo_uploader',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 270x270'),
        ),
        migrations.AddField(
            model_name='products_photo_uploader',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 270x270'),
        ),
        migrations.AlterField(
            model_name='products_photo_uploader',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='photo 270x270'),
        ),
        migrations.AlterField(
            model_name='products_photo_uploader',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 270x270'),
        ),
    ]
