# Generated by Django 3.0.1 on 2021-03-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210115_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage_main_banners',
            name='search_key',
            field=models.CharField(max_length=154, null=True),
        ),
    ]
