# Generated by Django 3.0.1 on 2021-04-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210408_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage_main_banners',
            options={'verbose_name': 'Home Page Main Banner (Mobile Apps)', 'verbose_name_plural': 'Home Page Main Banners (Mobile Apps)'},
        ),
        migrations.RemoveField(
            model_name='homepage_main_banners_website',
            name='search_key',
        ),
    ]
