# Generated by Django 3.0.8 on 2020-07-29 07:02

import django.core.validators
from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manfacturedate',
            name='manfacture_date',
        ),
        migrations.AddField(
            model_name='manfacturedate',
            name='manfacture_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1980), shop.models.max_value_current_year], verbose_name='year'),
        ),
    ]
