# Generated by Django 3.0.8 on 2020-07-29 07:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200729_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_capacity', models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(8000)], verbose_name='سعة الموتور')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Part Type', 'verbose_name_plural': 'Part Types'},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='model',
        ),
        migrations.RemoveField(
            model_name='model',
            name='engine_capacity',
        ),
        migrations.RemoveField(
            model_name='model',
            name='manfacture_dates',
        ),
        migrations.RemoveField(
            model_name='model',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partTypesBrand', to='shop.Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='manfacture_date',
            field=models.ManyToManyField(blank=True, to='shop.ManfactureDate'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partTypesModel', to='shop.Model'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='just leave this field blank if no sale available', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_capacity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partTypesEngCap', to='shop.EngineCapacity'),
        ),
    ]
