# Generated by Django 3.0.8 on 2020-08-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200729_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
