# Generated by Django 3.0.8 on 2020-08-10 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0003_auto_20160721_1127'),
        ('shop', '0008_auto_20200801_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=250)),
                ('Reply', models.TextField(blank=True, max_length=300, null=True)),
                ('rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='star_ratings.UserRating')),
            ],
        ),
    ]
