# Generated by Django 3.0.8 on 2020-08-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_reviewproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_per_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
