# Generated by Django 3.0.8 on 2020-08-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_max_per_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_per_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
