# Generated by Django 3.0.8 on 2020-08-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_min_per_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 270x270'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 800x800'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 800x800'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 800x800'),
        ),
        migrations.AddField(
            model_name='product',
            name='youtube_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='photo 160x110'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='photo 180x180'),
        ),
        migrations.AlterField(
            model_name='model',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='photo 640x400'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='photo 270x270'),
        ),
    ]
