# Generated by Django 3.0.8 on 2020-08-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_homepage_adds_homepage_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image2',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='photo 180x180'),
        ),
        migrations.AlterField(
            model_name='homepage_adds',
            name='slide_image',
            field=models.ImageField(upload_to='media/', verbose_name='Photo 1920x720'),
        ),
        migrations.AlterField(
            model_name='homepage_banners',
            name='banner_image',
            field=models.ImageField(upload_to='media/', verbose_name='Photo 640x400'),
        ),
    ]
