# Generated by Django 3.0.8 on 2020-08-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200825_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_banner',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='photo 870x220'),
        ),
    ]
