# Generated by Django 3.0.8 on 2020-08-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200825_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=154)),
                ('title', models.TextField(max_length=300)),
                ('paragraph_1_heading', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_1', models.TextField(max_length=5000)),
                ('paragraph_2_heading', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_2', models.TextField(blank=True, max_length=5000, null=True)),
                ('paragraph_3_heading', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_3', models.TextField(blank=True, max_length=5000, null=True)),
                ('image', models.ImageField(upload_to='media/', verbose_name='Photo 900x600')),
                ('image2', models.ImageField(upload_to='media/', verbose_name='Photo 270x420')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('tag', models.ManyToManyField(to='shop.Blog_tags')),
            ],
        ),
    ]
