# Generated by Django 3.0.8 on 2020-08-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20200827_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='This field will be filled automatically', max_length=100),
        ),
    ]
