# Generated by Django 3.0.8 on 2020-08-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20200827_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_arabic',
            field=models.CharField(max_length=154, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='paragraph_1_arabic',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='paragraph_1_heading_arabic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='paragraph_2_arabic',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='paragraph_2_heading_arabic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='paragraph_3_arabic',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='paragraph_3_heading_arabic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_arabic',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog_tags',
            name='tag_arabic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
