# Generated by Django 3.0.8 on 2020-09-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20200902_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_tags',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(help_text='This field only contains letters numbers and hyphens , No spaces', max_length=100, null=True, verbose_name='commercial title'),
        ),
        migrations.AlterField(
            model_name='blog_tags',
            name='tag',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
