# Generated by Django 3.0.8 on 2020-09-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms_and_privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_headline', models.CharField(max_length=220)),
                ('terms_parachraph', models.TextField(max_length=40000)),
                ('terms_release_date', models.DateField()),
                ('privacy_headline', models.CharField(max_length=220)),
                ('privacy_parachraph', models.TextField(max_length=40000)),
                ('privacy_release_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ManyToManyField(blank=True, null=True, related_name='partTypesModel', to='shop.Model'),
        ),
    ]
