# Generated by Django 3.0.8 on 2020-09-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20200905_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modelTest',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
