# Generated by Django 3.0.8 on 2020-09-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20200906_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.ManyToManyField(blank=True, related_name='partTypesModel', to='shop.Model'),
        ),
    ]
