# Generated by Django 3.0.8 on 2020-09-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20200907_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(help_text='This field only contains letters numbers and hyphens , No spaces', max_length=100, null=True, unique=True, verbose_name='commercial title'),
        ),
        migrations.AlterField(
            model_name='blog_tags',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
