# Generated by Django 3.0.1 on 2020-10-06 10:47

import django.core.validators
from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20200910_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manfacturedate',
            name='manfacture_year',
            field=models.CharField(max_length=4, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1980), shop.models.max_value_current_year], verbose_name='year'),
        ),
    ]
