# Generated by Django 3.0.1 on 2020-10-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactus',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
