# Generated by Django 3.0.1 on 2021-05-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_auto_20210520_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
