# Generated by Django 3.0.1 on 2021-06-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_product_free_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part_Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('name_arabic', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='rim_size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_height',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_width',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manfacture_date',
            field=models.ManyToManyField(blank=True, related_name='manfYears', to='shop.ManfactureDate'),
        ),
        migrations.AddField(
            model_name='product',
            name='part_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partbrand', to='shop.Part_Brand'),
        ),
    ]
