# Generated by Django 3.0.1 on 2021-06-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_auto_20210624_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tires',
            field=models.BooleanField(default=False),
        ),
    ]
