# Generated by Django 3.0.1 on 2021-07-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_product_tires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquid_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('name_arabic', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='part_brand',
            name='liquid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='liquids',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Liquids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_Brand_Liquids', to='shop.Part_Brand')),
                ('liquid_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquid_Type', to='shop.Liquid_type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Liquid_Product', to='shop.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='liquid_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquids_Types', to='shop.Liquid_type'),
        ),
    ]
