# Generated by Django 3.0.1 on 2021-07-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_auto_20210702_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liquids',
        ),
    ]
