# Generated by Django 3.0.1 on 2021-07-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_delete_liquids'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquid_type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='photo 270x270'),
        ),
        migrations.AddField(
            model_name='part_brand',
            name='image',
            field=models.ImageField(blank=True, help_text='add photo if the brand is of liquids and oils only', null=True, upload_to='media/', verbose_name='photo 270x270'),
        ),
        migrations.AlterField(
            model_name='part_brand',
            name='liquid',
            field=models.BooleanField(default=False, verbose_name='Is Liquid'),
        ),
        migrations.AlterField(
            model_name='product',
            name='liquids',
            field=models.BooleanField(default=False, verbose_name='Is Liquid'),
        ),
    ]
