# Generated by Django 3.0.1 on 2021-07-14 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_auto_20210713_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tire_width_num',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Tire_width'),
        ),
    ]
