# Generated by Django 3.0.1 on 2021-07-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_auto_20210714_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tire_height_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Tire_height'),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_rim_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Rim_size'),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_width_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Tire_width'),
        ),
    ]
