# Generated by Django 3.0.1 on 2021-07-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_auto_20210714_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rim_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tire_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tire_width',
        ),
    ]
