# Generated by Django 3.0.1 on 2021-07-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_auto_20210714_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tire_height_num',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tire_rim_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tire_width_num',
        ),
    ]
