# Generated by Django 3.0.1 on 2021-07-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_auto_20210714_1705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rim_size',
        ),
        migrations.DeleteModel(
            name='Tire_height',
        ),
        migrations.DeleteModel(
            name='Tire_width',
        ),
    ]
