# Generated by Django 3.0.1 on 2021-07-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_auto_20210714_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rim_size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rim_size', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tire_height',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rim_stire_heightize', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tire_width',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire_width', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tire_height_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Tire_height'),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_rim_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Rim_size'),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_width_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Tire_width'),
        ),
    ]
