# Generated by Django 3.0.1 on 2021-07-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_auto_20210714_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rim_size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_height',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tire_width',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
