# Generated by Django 3.0.1 on 2021-07-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_auto_20210714_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tire_height',
            old_name='rim_stire_heightize',
            new_name='tire_height',
        ),
    ]
