# Generated by Django 3.0.1 on 2021-07-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_auto_20210715_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rim_size',
            name='rim_size',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='tire_height',
            name='tire_height',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='tire_width',
            name='tire_width',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
