# Generated by Django 3.0.1 on 2021-07-17 10:09

from django.db import migrations, models
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0068_auto_20210715_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('purchasing_manager_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('comercial_and_tax_pdf', models.FileField(upload_to='media/merchants-files', validators=[shop.validators.validate_file_extension])),
                ('quotation', models.FileField(upload_to='media/merchants-files', validators=[shop.validators.validate_file_extension])),
                ('supplier', models.BooleanField(default=False)),
                ('buyer', models.BooleanField(default=False)),
                ('answered', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
