# Generated by Django 3.0.8 on 2020-08-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_city', models.CharField(max_length=50, unique=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
