# Generated by Django 3.0.1 on 2020-10-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200827_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcosts',
            name='shipping_city_arabic',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
