# Generated by Django 3.0.1 on 2020-10-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20201009_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='we_accept_transaction_id',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
