# Generated by Django 3.0.1 on 2020-10-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_we_accept_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_to_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
