# Generated by Django 3.0.1 on 2020-10-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20201015_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashOnDelivery',
            field=models.BooleanField(default=False),
        ),
    ]
