# Generated by Django 3.0.1 on 2020-10-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_cashondelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pormotionName', models.CharField(max_length=50, unique=True)),
                ('discount_ratio', models.IntegerField(max_length=2)),
                ('promo_code', models.CharField(max_length=50, unique=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Promo Codes',
            },
        ),
    ]
