# Generated by Django 3.0.1 on 2020-10-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_promocodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_before_promo_code',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='promocodes',
            name='discount_ratio',
            field=models.IntegerField(),
        ),
    ]
